services:
  warrior:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: archiveteam-warrior
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - DOWNLOADER=vasenka88
      - SELECTED_PROJECT=auto
      - CONCURRENT_ITEMS=6
      - WARRIOR_RUN_DIR=/warrior
    volumes:
      - /mnt/Seagate_3000/warrior:/warrior
